### ISSUE TITLE
Cannot toggle with keyboard shortcut in components with numeric characters in name

### ISSUE THREAD

**Issue by alanlalonde** [Oreoz/ember-shortcuts#4]
Keyboard toggle shortcut (CTRL + ALT + E) does not work when navigating between handlebars and javascript files for components that have numbers in their name. Ex: test-1a does not toggle with shortcut.

Works when using ALT + Enter shortcut for contextual menu.

**Comment by Oreoz** [comment]
Should now be fixed in 2.0.1.
